### ISSUE TITLE
Bounty: Possible minor gas & safety improvements

### ISSUE THREAD

**Issue by gabrocheleau** [ethorse/ethorse-core#39]
Hi guys.

1. In the function __callback, at line 108, there seems to be an unused argument (bytes proof). 
2. There are several spots where events are invoked without the "emit" prefix. (Lines 117, 120, 138, 147, 152, 274 of Betting.sol). This seems to be deprecated
3. In the calculateReward function, why not use safeMath to add the reward to winner_reward? (line 248 and 254). 
4. All eight of the oraclize_query calls in both contracts are unencrypted (and most importantly, six of them are using http, and not https!!). This might be an intended feature of the smart contract, but encrypting them would make it harder for attackers to target the information source.

**Comment by ethorse** [comment]
#42 
1. Even though we are not using the `bytes proof`,  If we don't include the argument that would make it a different function (function overloading)
2. These were fixed in the latest contract
3. The `calculateReward` function does not have any user input and this safemath is not used in a attempt to reduce the gas.
4. https has been implemented in the above-mentioned PR and not encrypted to have transparency. We will encrypt them when there is a necessity to use a API Key with the GET request.

**Comment by ethorse** [comment]
#42

Even though we don't use the bytes proof, without the argument it would make it a different function (function overloading)
These were fixed in the latest contract
The calculateReward function does not have any user input and this safemath is not used in an attempt to reduce the gas.
https has been implemented in the above-mentioned PR and not encrypted to have transparency. We will encrypt them when there is a necessity to use an API Key with the GET request.

**Comment by ethorse** [comment]
#42

1. Even though we don't use the bytes proof, without the argument it would make it a different function (function overloading)
2. These were fixed in the latest contract
3. The calculateReward function does not have any user input and this safemath is not used in an attempt to reduce the gas.
4. https has been implemented in the above-mentioned PR and not encrypted to have transparency. We will encrypt them when there is a necessity to use an API Key with the GET request.
