### ISSUE TITLE
Malicious owner can steal all money in races lasting longer than 30 days.

### ISSUE THREAD

**Issue by 08xmt** [ethorse/ethorse-core#9]
The owner would start by setting up a legitimate looking race, lasting longer than 30 days, getting people to bet on it.

After that, he would call the update function, with a delay that is over 30 days.
The locking duration in the function call would be set to a value, large enough to cause an overflow in the delay variable, on line 167.
This will set the race_duration = 0, and also query 3 oraclize queries right away.
Since the race is started, but it will be a very long time until it ends, the owner will just have to wait 30 days, before calling kill_refund() and recovery() in quick succession.

This can be easily mitigated by employing safemath functions inside the update function. Alternatively, voided bets could be unrecoverable for the owner, in the recovery function.

**Comment by ethorse** [comment]
#17

**Comment by ethorse** [comment]
#17 

malicious owner attack mitigated in more than one way. To be exact  #in three places.

- Updated the recovery to start_time + race_duration + 30days
- the race duration cannot be overflowed since safe math is employed.
- Any other type of malicious attacks is also mitigated by preventing reentrancy to update function.
